openapi: 3.0.1
info:
  title: Text Translation
  description: "Text translation is a cloud-based REST API feature of the Translator service that uses neural\nmachine translation technology to enable quick and accurate source-to-target text translation\nin real time across all supported languages.\n\nThe following methods are supported by the Text Translation feature:\n\nLanguages. Returns a list of languages supported by Translate, Transliterate, and Dictionary Lookup operations.\n\nTranslate. Renders single source-language text to multiple target-language texts with a single request.\n\nTransliterate. Converts characters or letters of a source language to the corresponding characters or letters of a target language.\n\nDetect. Returns the source code language code and a boolean variable denoting whether the detected language is supported for text translation and transliteration."
  version: '1.0'
servers:
  - url: https://red-scus-apimdemo-dev.azure-api.net/text-translate
paths:
  /breaksentence:
    post:
      summary: Find Sentence Boundaries
      description: Find Sentence Boundaries
      operationId: FindSentenceBoundaries
      parameters:
        - name: api-version
          in: query
          description: Mandatory API version parameter
          required: true
          schema:
            type: string
        - name: language
          in: query
          description: "Language tag identifying the language of the input text. \nIf a code isn't specified, automatic language detection will be applied."
          schema:
            type: string
        - name: script
          in: query
          description: "Script tag identifying the script used by the input text. \nIf a script isn't specified, the default script of the language will be assumed."
          schema:
            type: string
        - name: X-ClientTraceId
          in: header
          description: A client-generated GUID to uniquely identify the request.
          schema:
            type: string
      requestBody:
        description: Defines the content of the request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputTextItemArray'
            example:
              - text: string
      responses:
        '200':
          description: Response for the Break SEntence API.
          headers:
            X-RequestId:
              description: Value generated by the service to identify the request. It is used for troubleshooting purposes.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BreakSentenceItemArray'
              example:
                - detectedLanguage:
                    language: string
                    score: 0
                  sentLen:
                    - 0
        '500':
          description: An unexpected error response.
          headers:
            X-RequestId:
              description: Value generated by the service to identify the request. It is used for troubleshooting purposes.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  code: 0
                  message: string
  /dictionary/examples:
    post:
      summary: Lookup Dictionary Examples
      description: Lookup Dictionary Examples
      operationId: LookupDictionaryExamples
      parameters:
        - name: from
          in: query
          description: "Specifies the language of the input text.\nThe source language must be one of the supported languages included in the dictionary scope."
          required: true
          schema:
            type: string
        - name: to
          in: query
          description: "Specifies the language of the output text.\nThe target language must be one of the supported languages included in the dictionary scope."
          required: true
          schema:
            type: string
        - name: api-version
          in: query
          description: Mandatory API version parameter
          required: true
          schema:
            type: string
        - name: X-ClientTraceId
          in: header
          description: A client-generated GUID to uniquely identify the request.
          schema:
            type: string
      requestBody:
        description: Defines the content of the request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DictionaryExampleTextItemArray'
            example:
              - translation: string
                text: string
      responses:
        '200':
          description: Response for the dictionary examples API.
          headers:
            X-RequestId:
              description: Value generated by the service to identify the request. It is used for troubleshooting purposes.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DictionaryExampleItemArray'
              example:
                - normalizedSource: string
                  normalizedTarget: string
                  examples:
                    - sourcePrefix: string
                      sourceTerm: string
                      sourceSuffix: string
                      targetPrefix: string
                      targetTerm: string
                      targetSuffix: string
        '500':
          description: An unexpected error response.
          headers:
            X-RequestId:
              description: Value generated by the service to identify the request. It is used for troubleshooting purposes.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  code: 0
                  message: string
  /dictionary/lookup:
    post:
      summary: Lookup Dictionary Entries
      description: Lookup Dictionary Entries
      operationId: LookupDictionaryEntries
      parameters:
        - name: from
          in: query
          description: "Specifies the language of the input text.\nThe source language must be one of the supported languages included in the dictionary scope."
          required: true
          schema:
            type: string
        - name: to
          in: query
          description: "Specifies the language of the output text.\nThe target language must be one of the supported languages included in the dictionary scope."
          required: true
          schema:
            type: string
        - name: api-version
          in: query
          description: Mandatory API version parameter
          required: true
          schema:
            type: string
        - name: X-ClientTraceId
          in: header
          description: A client-generated GUID to uniquely identify the request.
          schema:
            type: string
      requestBody:
        description: Defines the content of the request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputTextItemArray'
            example:
              - text: string
      responses:
        '200':
          description: Response for the dictionary lookup API.
          headers:
            X-RequestId:
              description: Value generated by the service to identify the request. It is used for troubleshooting purposes.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DictionaryLookupItemArray'
              example:
                - normalizedSource: string
                  displaySource: string
                  translations:
                    - normalizedTarget: string
                      displayTarget: string
                      posTag: string
                      confidence: 0
                      prefixWord: string
                      backTranslations:
                        - normalizedText: string
                          displayText: string
                          numExamples: 0
                          frequencyCount: 0
        '500':
          description: An unexpected error response.
          headers:
            X-RequestId:
              description: Value generated by the service to identify the request. It is used for troubleshooting purposes.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  code: 0
                  message: string
  /languages:
    get:
      summary: Gets the set of languages currently supported by other operations of the Translator.
      description: Gets the set of languages currently supported by other operations of the Translator.
      operationId: GetSupportedLanguages
      parameters:
        - name: api-version
          in: query
          description: Mandatory API version parameter
          required: true
          schema:
            type: string
        - name: scope
          in: query
          description: "A comma-separated list of names defining the group of languages to return.\nAllowed group names are: `translation`, `transliteration` and `dictionary`.\nIf no scope is given, then all groups are returned, which is equivalent to passing \n`scope=translation,transliteration,dictionary`. To decide which set of supported languages \nis appropriate for your scenario, see the description of the [response object](#response-body)."
          schema:
            type: string
        - name: X-ClientTraceId
          in: header
          description: A client-generated GUID to uniquely identify the request.
          schema:
            type: string
        - name: Accept-Language
          in: header
          description: "The language to use for user interface strings. Some of the fields in the response are names of languages or \nnames of regions. Use this parameter to define the language in which these names are returned. \nThe language is specified by providing a well-formed BCP 47 language tag. For instance, use the value `fr` \nto request names in French or use the value `zh-Hant` to request names in Chinese Traditional.\nNames are provided in the English language when a target language is not specified or when localization \nis not available."
          schema:
            type: string
            default: en
        - name: If-None-Match
          in: header
          description: "Passing the value of the ETag response header in an If-None-Match field will allow the service to optimize the response. \nIf the resource has not been modified, the service will return status code 304 and an empty response body."
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          headers:
            ETag:
              description: "Current value of the entity tag for the requested groups of supported languages. \nTo make subsequent requests more efficient, the client may send the `ETag` value in an \n`If-None-Match` header field."
              schema:
                type: string
            X-RequestId:
              description: Value generated by the service to identify the request. It is used for troubleshooting purposes.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSupportedLanguagesResult'
              example:
                translation: { }
                transliteration: { }
                dictionary: { }
        '500':
          description: An unexpected error response.
          headers:
            X-RequestId:
              description: Value generated by the service to identify the request. It is used for troubleshooting purposes.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  code: 0
                  message: string
  /translate:
    post:
      summary: Translate Text
      description: Translate Text
      operationId: Translate
      parameters:
        - name: to
          in: query
          description: "Specifies the language of the output text. The target language must be one of the supported languages included \nin the translation scope. For example, use to=de to translate to German.\nIt's possible to translate to multiple languages simultaneously by repeating the parameter in the query string. \nFor example, use to=de&to=it to translate to German and Italian."
          required: true
          schema:
            type: array
            items:
              type: string
        - name: api-version
          in: query
          description: Mandatory API version parameter
          required: true
          schema:
            type: string
        - name: from
          in: query
          description: "Specifies the language of the input text. Find which languages are available to translate from by \nlooking up supported languages using the translation scope. If the from parameter isn't specified, \nautomatic language detection is applied to determine the source language.\n\nYou must use the from parameter rather than autodetection when using the dynamic dictionary feature. \nNote: the dynamic dictionary feature is case-sensitive."
          schema:
            type: string
        - name: textType
          in: query
          description: "Defines whether the text being translated is plain text or HTML text. Any HTML needs to be a well-formed, \ncomplete element. Possible values are: plain (default) or html."
          schema:
            enum:
              - Plain
              - Html
            type: string
            default: Plain
        - name: category
          in: query
          description: "A string specifying the category (domain) of the translation. This parameter is used to get translations \nfrom a customized system built with Custom Translator. Add the Category ID from your Custom Translator \nproject details to this parameter to use your deployed customized system. Default value is: general."
          schema:
            type: string
            default: general
        - name: profanityAction
          in: query
          description: "Specifies how profanities should be treated in translations.\nPossible values are: NoAction (default), Marked or Deleted."
          schema:
            enum:
              - NoAction
              - Marked
              - Deleted
            type: string
            default: NoAction
        - name: profanityMarker
          in: query
          description: "Specifies how profanities should be marked in translations.\nPossible values are: Asterisk (default) or Tag. "
          schema:
            enum:
              - Asterisk
              - Tag
            type: string
            default: Asterisk
        - name: includeAlignment
          in: query
          description: "Specifies whether to include alignment projection from source text to translated text.\nPossible values are: true or false (default)."
          schema:
            type: boolean
            default: false
        - name: includeSentenceLength
          in: query
          description: "Specifies whether to include sentence boundaries for the input text and the translated text.\nPossible values are: true or false (default)."
          schema:
            type: boolean
            default: false
        - name: suggestedFrom
          in: query
          description: "Specifies a fallback language if the language of the input text can't be identified. \nLanguage autodetection is applied when the from parameter is omitted. If detection fails, \nthe suggestedFrom language will be assumed."
          schema:
            type: string
        - name: fromScript
          in: query
          description: Specifies the script of the input text.
          schema:
            type: string
        - name: toScript
          in: query
          description: Specifies the script of the translated text.
          schema:
            type: string
        - name: allowFallback
          in: query
          description: "Specifies that the service is allowed to fall back to a general system when a custom system doesn't exist. \nPossible values are: true (default) or false.\n\nallowFallback=false specifies that the translation should only use systems trained for the category specified \nby the request. If a translation for language X to language Y requires chaining through a pivot language E, \nthen all the systems in the chain (X → E and E → Y) will need to be custom and have the same category. \nIf no system is found with the specific category, the request will return a 400 status code. allowFallback=true \nspecifies that the service is allowed to fall back to a general system when a custom system doesn't exist."
          schema:
            type: boolean
            default: true
        - name: X-ClientTraceId
          in: header
          description: A client-generated GUID to uniquely identify the request.
          schema:
            type: string
      requestBody:
        description: Defines the content of the request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputTextItemArray'
            example:
              - text: string
      responses:
        '200':
          description: Response for the translation API.
          headers:
            X-RequestId:
              description: Value generated by the service to identify the request. It is used for troubleshooting purposes.
              schema:
                type: string
            x-metered-usage:
              description: "Specifies consumption (the number of characters for which the user will be charged) for the translation \njob request. For example, if the word \"Hello\" is translated from English (en) to French (fr), \nthis field will return the value '5'."
              schema:
                type: integer
                format: int32
            x-mt-system:
              description: "Specifies the system type that was used for translation for each 'to' language requested for translation. \nThe value is a comma-separated list of strings. Each string indicates a type:\n\n* Custom - Request includes a custom system and at least one custom system was used during translation.\n* Team - All other requests"
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TranslatedTextItemArray'
              example:
                - detectedLanguage:
                    language: string
                    score: 0
                  translations:
                    - to: string
                      text: string
                      transliteration:
                        text: string
                        script: string
                      alignment:
                        proj: string
                      sentLen:
                        srcSentLen:
                          - 0
                        transSentLen:
                          - 0
                  sourceText:
                    text: string
        '500':
          description: An unexpected error response.
          headers:
            X-RequestId:
              description: Value generated by the service to identify the request. It is used for troubleshooting purposes.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  code: 0
                  message: string
  /transliterate:
    post:
      summary: Transliterate Text
      description: Transliterate Text
      operationId: Transliterate
      parameters:
        - name: language
          in: query
          description: "Specifies the language of the text to convert from one script to another. \nPossible languages are listed in the transliteration scope obtained by querying the service \nfor its supported languages."
          required: true
          schema:
            type: string
        - name: fromScript
          in: query
          description: "Specifies the script used by the input text. Look up supported languages using the transliteration scope,\nto find input scripts available for the selected language."
          required: true
          schema:
            type: string
        - name: toScript
          in: query
          description: "Specifies the output script. Look up supported languages using the transliteration scope, to find output \nscripts available for the selected combination of input language and input script."
          required: true
          schema:
            type: string
        - name: api-version
          in: query
          description: Mandatory API version parameter
          required: true
          schema:
            type: string
        - name: X-ClientTraceId
          in: header
          description: A client-generated GUID to uniquely identify the request.
          schema:
            type: string
      requestBody:
        description: Defines the content of the request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputTextItemArray'
            example:
              - text: string
      responses:
        '200':
          description: Response for the transliteration API.
          headers:
            X-RequestId:
              description: Value generated by the service to identify the request. It is used for troubleshooting purposes.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransliteratedTextArray'
              example:
                - text: string
                  script: string
        '500':
          description: An unexpected error response.
          headers:
            X-RequestId:
              description: Value generated by the service to identify the request. It is used for troubleshooting purposes.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  code: 0
                  message: string
components:
  schemas:
    BackTranslation:
      required:
        - normalizedText
        - displayText
        - numExamples
        - frequencyCount
      type: object
      properties:
        normalizedText:
          type: string
          description: "A string giving the normalized form of the source term that is a back-translation of the target.\nThis value should be used as input to lookup examples."
        displayText:
          type: string
          description: "A string giving the source term that is a back-translation of the target in a form best\nsuited for end-user display."
        numExamples:
          type: integer
          description: "An integer representing the number of examples that are available for this translation pair.\nActual examples must be retrieved with a separate call to lookup examples. The number is mostly\nintended to facilitate display in a UX. For example, a user interface may add a hyperlink\nto the back-translation if the number of examples is greater than zero and show the back-translation\nas plain text if there are no examples. Note that the actual number of examples returned\nby a call to lookup examples may be less than numExamples, because additional filtering may be\napplied on the fly to remove \"bad\" examples."
          format: int32
        frequencyCount:
          type: integer
          description: "An integer representing the frequency of this translation pair in the data. The main purpose of this\nfield is to provide a user interface with a means to sort back-translations so the most frequent terms are first."
          format: int32
      description: Back Translation
    BreakSentenceItem:
      required:
        - sentLen
      type: object
      properties:
        detectedLanguage:
          $ref: '#/components/schemas/DetectedLanguage'
        sentLen:
          type: array
          items:
            type: integer
            format: int32
          description: "An integer array representing the lengths of the sentences in the input text.\nThe length of the array is the number of sentences, and the values are the length of each sentence."
      description: Item containing break sentence result.
    BreakSentenceResult:
      required:
        - result
      type: object
      properties:
        result:
          type: array
          items:
            $ref: '#/components/schemas/BreakSentenceItem'
          description: Array of the break sentence elements.
      description: Response for the Break SEntence API.
    DetectedLanguage:
      required:
        - language
        - score
      type: object
      properties:
        language:
          type: string
          description: A string representing the code of the detected language.
        score:
          type: number
          description: "A float value indicating the confidence in the result.\nThe score is between zero and one and a low score indicates a low confidence."
          format: float
      description: An object describing the detected language.
    DictionaryExample:
      required:
        - sourcePrefix
        - sourceTerm
        - sourceSuffix
        - targetPrefix
        - targetTerm
        - targetSuffix
      type: object
      properties:
        sourcePrefix:
          type: string
          description: "The string to concatenate before the value of sourceTerm to form a complete example.\nDo not add a space character, since it is already there when it should be.\nThis value may be an empty string."
        sourceTerm:
          type: string
          description: "A string equal to the actual term looked up. The string is added with sourcePrefix\nand sourceSuffix to form the complete example. Its value is separated so it can be\nmarked in a user interface, e.g., by bolding it."
        sourceSuffix:
          type: string
          description: "The string to concatenate after the value of sourceTerm to form a complete example.\nDo not add a space character, since it is already there when it should be.\nThis value may be an empty string."
        targetPrefix:
          type: string
          description: A string similar to sourcePrefix but for the target.
        targetTerm:
          type: string
          description: A string similar to sourceTerm but for the target.
        targetSuffix:
          type: string
          description: A string similar to sourceSuffix but for the target.
      description: Dictionary Example
    DictionaryExampleItem:
      required:
        - normalizedSource
        - normalizedTarget
        - examples
      type: object
      properties:
        normalizedSource:
          type: string
          description: "A string giving the normalized form of the source term. Generally, this should be identical\nto the value of the Text field at the matching list index in the body of the request."
        normalizedTarget:
          type: string
          description: "A string giving the normalized form of the target term. Generally, this should be identical\nto the value of the Translation field at the matching list index in the body of the request."
        examples:
          type: array
          items:
            $ref: '#/components/schemas/DictionaryExample'
          description: 'A list of examples for the (source term, target term) pair.'
      description: Dictionary Example element
    DictionaryExampleTextItem:
      required:
        - translation
      type: object
      allOf:
        - $ref: '#/components/schemas/InputTextItem'
      properties:
        translation:
          type: string
          description: "A string specifying the translated text previously returned by the Dictionary lookup operation. \nThis should be the value from the normalizedTarget field in the translations list of the Dictionary \nlookup response. The service will return examples for the specific source-target word-pair."
      description: Element containing the text with translation.
    DictionaryExamplesResult:
      required:
        - result
      type: object
      properties:
        result:
          type: array
          items:
            $ref: '#/components/schemas/DictionaryExampleItem'
          description: Array of the dictionary examples elements.
      description: Response for the dictionary examples API.
    DictionaryLookupItem:
      required:
        - normalizedSource
        - displaySource
        - translations
      type: object
      properties:
        normalizedSource:
          type: string
          description: "A string giving the normalized form of the source term.\nFor example, if the request is \"JOHN\", the normalized form will be \"john\".\nThe content of this field becomes the input to lookup examples."
        displaySource:
          type: string
          description: "A string giving the source term in a form best suited for end-user display.\nFor example, if the input is \"JOHN\", the display form will reflect the usual\nspelling of the name: \"John\"."
        translations:
          type: array
          items:
            $ref: '#/components/schemas/DictionaryTranslation'
          description: A list of translations for the source term.
      description: Dictionary Lookup Element
    DictionaryLookupResult:
      required:
        - result
      type: object
      properties:
        result:
          type: array
          items:
            $ref: '#/components/schemas/DictionaryLookupItem'
          description: Array of the dictionary lookup elements.
      description: Response for the dictionary lookup API.
    DictionaryTranslation:
      required:
        - normalizedTarget
        - displayTarget
        - posTag
        - confidence
        - prefixWord
        - backTranslations
      type: object
      properties:
        normalizedTarget:
          type: string
          description: "A string giving the normalized form of this term in the target language.\nThis value should be used as input to lookup examples."
        displayTarget:
          type: string
          description: "A string giving the term in the target language and in a form best suited\nfor end-user display. Generally, this will only differ from the normalizedTarget\nin terms of capitalization. For example, a proper noun like \"Juan\" will have\nnormalizedTarget = \"juan\" and displayTarget = \"Juan\"."
        posTag:
          type: string
          description: A string associating this term with a part-of-speech tag.
        confidence:
          type: number
          description: "A value between 0.0 and 1.0 which represents the \"confidence\" \n(or perhaps more accurately, \"probability in the training data\") of that translation pair. \nThe sum of confidence scores for one source word may or may not sum to 1.0."
          format: float
        prefixWord:
          type: string
          description: "A string giving the word to display as a prefix of the translation. Currently,\nthis is the gendered determiner of nouns, in languages that have gendered determiners.\nFor example, the prefix of the Spanish word \"mosca\" is \"la\", since \"mosca\" is a feminine noun in Spanish. \nThis is only dependent on the translation, and not on the source. \nIf there is no prefix, it will be the empty string."
        backTranslations:
          type: array
          items:
            $ref: '#/components/schemas/BackTranslation'
          description: "A list of \"back translations\" of the target. For example, source words that the target can translate to.\nThe list is guaranteed to contain the source word that was requested (e.g., if the source word being\nlooked up is \"fly\", then it is guaranteed that \"fly\" will be in the backTranslations list).\nHowever, it is not guaranteed to be in the first position, and often will not be."
      description: Translation source term.
    ErrorDetails:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: integer
          description: Number identifier of the error.
          format: int32
        message:
          type: string
          description: Human readable error description.
      description: Error details as returned by Translator Service.
    ErrorResponse:
      required:
        - error
      type: object
      properties:
        error:
          $ref: '#/components/schemas/ErrorDetails'
      description: Representation of the Error Response from Translator Service.
    GetSupportedLanguagesResult:
      type: object
      properties:
        translation:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/TranslationLanguage'
          description: Languages that support translate API.
        transliteration:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/TransliterationLanguage'
          description: Languages that support transliteration API.
        dictionary:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/SourceDictionaryLanguage'
          description: Languages that support dictionary API.
      description: Response for the languages API.
    InputTextItem:
      required:
        - text
      type: object
      properties:
        text:
          type: string
          description: Text to translate.
      description: Element containing the text for translation.
    LanguageDirectionality:
      enum:
        - ltr
        - rtl
      type: string
      description: Language Directionality
      x-ms-enum:
        name: LanguageDirectionality
        modelAsString: false
        values:
          - name: LeftToRight
            value: ltr
            description: Language is written left to right.
          - name: RightToLeft
            value: rtl
            description: Language is written right to left.
    LanguageScript:
      required:
        - code
        - name
        - nativeName
        - dir
      type: object
      properties:
        code:
          type: string
          description: Code identifying the script.
        name:
          type: string
          description: Display name of the script in the locale requested via Accept-Language header.
        nativeName:
          type: string
          description: Display name of the language in the locale native for the language.
        dir:
          $ref: '#/components/schemas/LanguageDirectionality'
      description: Common properties of language script
    ProfanityAction:
      enum:
        - NoAction
        - Marked
        - Deleted
      type: string
      description: Translator profanity actions
      x-ms-enum:
        name: ProfanityAction
        modelAsString: false
        values:
          - name: NoAction
            value: NoAction
            description: No Action is taken on profanity
          - name: Marked
            value: Marked
            description: Profanity is marked.
          - name: Deleted
            value: Deleted
            description: Profanity is deleted from the translated text.
    ProfanityMarker:
      enum:
        - Asterisk
        - Tag
      type: string
      description: Translator profanity markers
      x-ms-enum:
        name: ProfanityMarker
        modelAsString: false
        values:
          - name: Asterisk
            value: Asterisk
            description: Profanity is marked with asterisk.
          - name: Tag
            value: Tag
            description: Profanity is marked with the tags.
    SentenceBoundaries:
      required:
        - srcSentLen
        - transSentLen
      type: object
      properties:
        srcSentLen:
          type: array
          items:
            type: integer
            format: int32
          description: "An integer array representing the lengths of the sentences in the input text. \nThe length of the array is the number of sentences, and the values are the length of each sentence."
        transSentLen:
          type: array
          items:
            type: integer
            format: int32
          description: "An integer array representing the lengths of the sentences in the translated text. \nThe length of the array is the number of sentences, and the values are the length of each sentence."
      description: An object returning sentence boundaries in the input and output texts.
    SourceDictionaryLanguage:
      required:
        - name
        - nativeName
        - dir
        - translations
      type: object
      properties:
        name:
          type: string
          description: Display name of the language in the locale requested via Accept-Language header.
        nativeName:
          type: string
          description: Display name of the language in the locale native for this language.
        dir:
          $ref: '#/components/schemas/LanguageDirectionality'
        translations:
          type: array
          items:
            $ref: '#/components/schemas/TargetDictionaryLanguage'
          description: List of languages with alterative translations and examples for the query expressed in the source language.
      description: Properties ot the source dictionary language
    SourceText:
      required:
        - text
      type: object
      properties:
        text:
          type: string
          description: Input text in the default script of the source language.
      description: 'Input text in the default script of the source language. '
    TargetDictionaryLanguage:
      required:
        - name
        - nativeName
        - dir
        - code
      type: object
      properties:
        name:
          type: string
          description: Display name of the language in the locale requested via Accept-Language header.
        nativeName:
          type: string
          description: Display name of the language in the locale native for this language.
        dir:
          $ref: '#/components/schemas/LanguageDirectionality'
        code:
          type: string
          description: Language code identifying the target language.
      description: Properties of the target dictionary language
    TextType:
      enum:
        - Plain
        - Html
      type: string
      description: Translation text type
      x-ms-enum:
        name: TextType
        modelAsString: true
        values:
          - name: Plain
            value: Plain
            description: Plain text.
          - name: Html
            value: Html
            description: HTML-encoded text.
    TranslatedTextAlignment:
      required:
        - proj
      type: object
      properties:
        proj:
          type: string
          description: "Maps input text to translated text. The alignment information is only provided when the request \nparameter includeAlignment is true. Alignment is returned as a string value of the following \nformat: [[SourceTextStartIndex]:[SourceTextEndIndex]–[TgtTextStartIndex]:[TgtTextEndIndex]]. \nThe colon separates start and end index, the dash separates the languages, and space separates the words. \nOne word may align with zero, one, or multiple words in the other language, and the aligned words may \nbe non-contiguous. When no alignment information is available, the alignment element will be empty."
      description: Alignment information object.
    TranslatedTextItem:
      required:
        - translations
      type: object
      properties:
        detectedLanguage:
          $ref: '#/components/schemas/DetectedLanguage'
        translations:
          type: array
          items:
            $ref: '#/components/schemas/TranslationText'
          description: "An array of translation results. The size of the array matches the number of target \nlanguages specified through the to query parameter."
        sourceText:
          $ref: '#/components/schemas/SourceText'
      description: Element containing the translated text
    TranslationLanguage:
      required:
        - name
        - nativeName
        - dir
      type: object
      properties:
        name:
          type: string
          description: Display name of the language in the locale requested via Accept-Language header.
        nativeName:
          type: string
          description: Display name of the language in the locale native for this language.
        dir:
          $ref: '#/components/schemas/LanguageDirectionality'
      description: "The value of the translation property is a dictionary of (key, value) pairs. Each key is a BCP 47 language tag.\nA key identifies a language for which text can be translated to or translated from."
    TranslationResult:
      required:
        - result
      type: object
      properties:
        result:
          type: array
          items:
            $ref: '#/components/schemas/TranslatedTextItem'
          description: Array of the translated text elements.
      description: Response for the translation API.
    TranslationText:
      required:
        - to
        - text
      type: object
      properties:
        to:
          type: string
          description: A string representing the language code of the target language.
        text:
          type: string
          description: A string giving the translated text.
        transliteration:
          $ref: '#/components/schemas/TransliteratedText'
        alignment:
          $ref: '#/components/schemas/TranslatedTextAlignment'
        sentLen:
          $ref: '#/components/schemas/SentenceBoundaries'
      description: Translation result
    TransliterableScript:
      required:
        - toScripts
      type: object
      allOf:
        - $ref: '#/components/schemas/LanguageScript'
      properties:
        toScripts:
          type: array
          items:
            $ref: '#/components/schemas/LanguageScript'
          description: List of scripts available to convert text to.
      description: Script definition with list of script into which given script can be translitered.
    TransliterateResult:
      required:
        - result
      type: object
      properties:
        result:
          type: array
          items:
            $ref: '#/components/schemas/TransliteratedText'
          description: Array of transliterated texts
      description: Response for the transliteration API.
    TransliteratedText:
      required:
        - text
        - script
      type: object
      properties:
        text:
          type: string
          description: A string which is the result of converting the input string to the output script.
        script:
          type: string
          description: A string specifying the script used in the output.
      description: Transliterated text element.
    TransliterationLanguage:
      required:
        - name
        - nativeName
        - scripts
      type: object
      properties:
        name:
          type: string
          description: Display name of the language in the locale requested via Accept-Language header.
        nativeName:
          type: string
          description: Display name of the language in the locale native for this language.
        scripts:
          type: array
          items:
            $ref: '#/components/schemas/TransliterableScript'
          description: List of scripts to convert from.
      description: "The value of the transliteration property is a dictionary of (key, value) pairs. \nEach key is a BCP 47 language tag. A key identifies a language for which text can be converted from one script \nto another script."
    InputTextItemArray:
      type: array
      items:
        $ref: '#/components/schemas/InputTextItem'
    BreakSentenceItemArray:
      type: array
      items:
        $ref: '#/components/schemas/BreakSentenceItem'
    DictionaryExampleTextItemArray:
      type: array
      items:
        $ref: '#/components/schemas/DictionaryExampleTextItem'
    DictionaryExampleItemArray:
      type: array
      items:
        $ref: '#/components/schemas/DictionaryExampleItem'
    DictionaryLookupItemArray:
      type: array
      items:
        $ref: '#/components/schemas/DictionaryLookupItem'
    TranslatedTextItemArray:
      type: array
      items:
        $ref: '#/components/schemas/TranslatedTextItem'
    TransliteratedTextArray:
      type: array
      items:
        $ref: '#/components/schemas/TransliteratedText'
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: api-key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]